table FactOnlineSales
	lineageTag: da932dc8-4af4-45f0-8752-68e7b7ef662b

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: month
		rollingWindowPeriods: 23
		incrementalGranularity: month
		incrementalPeriods: 1
		sourceExpression =
			let
			    Source = Sql.Database("Antonio\SQLEXPRESS", "ContosoRetailDW"),
			    dbo_FactOnlineSales = Source{[Schema="dbo",Item="FactOnlineSales"]}[Data],
			    #"Filtered Rows" = Table.SelectRows(dbo_FactOnlineSales, each [DateKey] >= RangeStart and [DateKey] < RangeEnd)
			in
			    #"Filtered Rows"

	column OnlineSalesKey
		dataType: int64
		formatString: 0
		lineageTag: b80171c8-b0a7-4cf4-a715-6d351d3ca5bb
		summarizeBy: count
		sourceColumn: OnlineSalesKey

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		formatString: General Date
		lineageTag: 38e19db4-322a-4e27-9071-50de74a488cb
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 0ca59cb3-74c2-47f5-8323-b4e51fedb9ac
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: d41ccbd7-1028-4f40-9f2a-ff692546048b
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: f2623715-ea57-4e75-8c58-bd0f9b1ccfe3
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 6ae9f988-bf36-4acd-91e6-f0249af16eb5
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 15333256-48bf-4919-be79-c854a9022ad5
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: 7ee8da4a-d18e-493c-96d5-e74f3472f049
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 080ee924-a17b-49e9-b694-10d4031f5398
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column SalesQuantity
		dataType: int64
		formatString: 0
		lineageTag: 0ee96bb4-9b07-4435-a370-170ce25a285c
		summarizeBy: sum
		sourceColumn: SalesQuantity

		annotation SummarizationSetBy = Automatic

	column SalesAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9b59f539-56a0-4406-a439-17129243c9c5
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: 780981fe-37c7-4a5f-86f8-9f06a5018541
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	column ReturnAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e850b868-3908-4858-b134-56b3f333e3c3
		summarizeBy: sum
		sourceColumn: ReturnAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column DiscountQuantity
		dataType: int64
		formatString: 0
		lineageTag: 45fdc76f-ae0a-40b6-8e08-5004500fd6b1
		summarizeBy: sum
		sourceColumn: DiscountQuantity

		annotation SummarizationSetBy = Automatic

	column DiscountAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 81e32b1e-273c-408c-b365-26c5f60e1c88
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column TotalCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 17914ccc-2119-494f-abe9-3b7a7211a633
		summarizeBy: sum
		sourceColumn: TotalCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column UnitCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 40c3f90c-1ab4-4a78-b5bb-534453ea097a
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ac681608-32bc-4683-ba1f-6010f2839f93
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column ETLLoadID
		dataType: int64
		formatString: 0
		lineageTag: 17f9ddbf-7ecd-407f-a890-479dafc1ddce
		summarizeBy: count
		sourceColumn: ETLLoadID

		annotation SummarizationSetBy = Automatic

	column LoadDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 740f9740-20c4-4e13-8a94-4da34a93a298
		summarizeBy: none
		sourceColumn: LoadDate

		annotation SummarizationSetBy = Automatic

	column UpdateDate
		dataType: dateTime
		formatString: General Date
		lineageTag: b34e8527-8bc7-4fd4-8237-8b630c875120
		summarizeBy: none
		sourceColumn: UpdateDate

		annotation SummarizationSetBy = Automatic

	partition FactOnlineSales = m
		mode: import
		source =
				let
				    Source = Sql.Database("Antonio\SQLEXPRESS", "ContosoRetailDW"),
				    dbo_FactOnlineSales = Source{[Schema="dbo",Item="FactOnlineSales"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_FactOnlineSales, each [DateKey] >= RangeStart and [DateKey] < RangeEnd)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_IsMQueryFoldable = True

	annotation PBI_NavigationStepName = Navigation

