{
  "compatibilityLevel": 1606,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"_Measures\",\"Dim_Jurisdiction\",\"Dim_CalendarYear\",\"Dim_GMA_2045_Target\",\"Dim_CAI_Employment_Benchmark\",\"Fact_Population\",\"Fact_HousingPermits\",\"Fact_Employment\",\"Fact_Housing_AMI\",\"SourceWorkbookPath\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "SourceWorkbookPath",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "File path to the master processed star schema Excel workbook.",
        "expression": "\"C:/SCOG_Data/SCOG_Star_Schema_Data_Model.xlsx\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9fd96072-0e55-4155-ac91-39fa36af133f"
      }
    ],
    "relationships": [
      {
        "name": "Rel_Jurisdiction_FactPopulation",
        "fromColumn": "Jurisdiction_ID",
        "fromTable": "Fact_Population",
        "toColumn": "Jurisdiction_ID",
        "toTable": "Dim_Jurisdiction"
      },
      {
        "name": "Rel_CalendarYear_FactPopulation",
        "fromColumn": "Year",
        "fromTable": "Fact_Population",
        "toColumn": "Year",
        "toTable": "Dim_CalendarYear"
      },
      {
        "name": "Rel_Jurisdiction_FactHousingPermits",
        "fromColumn": "Jurisdiction_ID",
        "fromTable": "Fact_HousingPermits",
        "toColumn": "Jurisdiction_ID",
        "toTable": "Dim_Jurisdiction"
      },
      {
        "name": "Rel_CalendarYear_FactHousingPermits",
        "fromColumn": "Year",
        "fromTable": "Fact_HousingPermits",
        "toColumn": "Year",
        "toTable": "Dim_CalendarYear"
      },
      {
        "name": "Rel_CalendarYear_FactEmployment",
        "fromColumn": "Year",
        "fromTable": "Fact_Employment",
        "toColumn": "Year",
        "toTable": "Dim_CalendarYear"
      },
      {
        "name": "Rel_Jurisdiction_FactHousingAMI",
        "fromColumn": "Jurisdiction_ID",
        "fromTable": "Fact_Housing_AMI",
        "toColumn": "Jurisdiction_ID",
        "toTable": "Dim_Jurisdiction"
      },
      {
        "name": "Rel_CalendarYear_FactHousingAMI",
        "fromColumn": "Year",
        "fromTable": "Fact_Housing_AMI",
        "toColumn": "Year",
        "toTable": "Dim_CalendarYear"
      },
      {
        "name": "Rel_Jurisdiction_DimGMATarget",
        "fromColumn": "Jurisdiction_ID",
        "fromTable": "Dim_GMA_2045_Target",
        "toColumn": "Jurisdiction_ID",
        "toTable": "Dim_Jurisdiction"
      },
      {
        "name": "Rel_CalendarYear_DimCAIBenchmark",
        "fromColumn": "Year",
        "fromTable": "Dim_CAI_Employment_Benchmark",
        "toColumn": "Year",
        "toTable": "Dim_CalendarYear"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "_Measures",
        "columns": [
          {
            "name": "Measure_Group",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "763612a7-abea-4dbd-95fe-5127ba8723d1",
            "sourceColumn": "Measure_Group"
          }
        ],
        "description": "Central repository for calculated DAX business logic and KPI metrics.",
        "lineageTag": "47e3b937-4458-40a6-a34d-53d93f25f419",
        "measures": [
          {
            "name": "Selected Reporting Year",
            "description": "Currently filtered calendar year, defaulting to prototype baseline 2025.",
            "displayFolder": "01. Executive & Governance",
            "expression": "COALESCE(SELECTEDVALUE(Dim_CalendarYear[Year]), 2025)",
            "formatString": "0",
            "lineageTag": "a289ef32-368b-446b-84df-1bf8e6cca84a"
          },
          {
            "name": "Selected Jurisdiction",
            "description": "Selected jurisdiction name or countywide indicator.",
            "displayFolder": "01. Executive & Governance",
            "expression": "SELECTEDVALUE(Dim_Jurisdiction[Jurisdiction_Name], \"All Skagit County Jurisdictions\")",
            "lineageTag": "60ee3c43-6411-4f3e-bbdc-6b856e88dcfe"
          },
          {
            "name": "Report Adoption Status Banner",
            "description": "Dynamic governance status indicator for Board adoption review.",
            "displayFolder": "01. Executive & Governance",
            "expression": [
              "VAR CurrentYr = [Selected Reporting Year]",
              "RETURN",
              "IF(CurrentYr <= 2024, \"BOARD ADOPTED (Official Legal Record)\", IF(CurrentYr = 2025, \"PROTOTYPE 2025 (Prior-Year Historical Calibration)\", \"PRELIMINARY 2026 (Under Review / Draft)\"))"
            ],
            "lineageTag": "cea11f07-655f-48d3-8e58-62c280bc3437"
          },
          {
            "name": "Metadata Footer Notice",
            "description": "Standardized audit attribution footer text required for Board PDF exports.",
            "displayFolder": "01. Executive & Governance",
            "expression": "\"Data Sources: WA Office of Financial Management (OFM) | Employment Security Department (ESD QCEW) | Skagit County GMA Allocations (Ordinance O20250002) | SCOG Annual Growth Monitoring Report\"",
            "lineageTag": "c28b6bb5-2a2c-4d6d-8176-190fcbea7860"
          },
          {
            "name": "Total Population",
            "description": "Total official population estimate from OFM April 1.",
            "displayFolder": "02. Population Growth & Targets",
            "expression": [
              "VAR LatestYr = [Selected Reporting Year]",
              "RETURN",
              "IF(",
              "    HASONEVALUE(Dim_Jurisdiction[Jurisdiction_Name]),",
              "    IF(",
              "        ISFILTERED(Dim_CalendarYear[Year]),",
              "        SUM(Fact_Population[Population_Count]),",
              "        CALCULATE(",
              "            SUM(Fact_Population[Population_Count]),",
              "            Dim_CalendarYear[Year] = LatestYr",
              "        )",
              "    ),",
              "    IF(",
              "        ISFILTERED(Dim_CalendarYear[Year]),",
              "        CALCULATE(",
              "            SUM(Fact_Population[Population_Count]),",
              "            Fact_Population[Data_Source_Type] = \"OFM_April1_Official_Determination\"",
              "        ),",
              "        CALCULATE(",
              "            SUM(Fact_Population[Population_Count]),",
              "            Dim_CalendarYear[Year] = LatestYr,",
              "            Fact_Population[Data_Source_Type] = \"OFM_April1_Official_Determination\"",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "253e9ab4-373c-4b83-9807-6e30c4b71e26"
          },
          {
            "name": "Prior Year Population",
            "description": "Population count in the prior calendar year.",
            "displayFolder": "02. Population Growth & Targets",
            "expression": "CALCULATE([Total Population], SAMEPERIODLASTYEAR(Dim_CalendarYear[Year]))",
            "formatString": "#,##0",
            "lineageTag": "9c36b1c0-fec1-4bf1-9703-157c8365beed"
          },
          {
            "name": "YoY Population Change",
            "description": "Net annual population change relative to prior year.",
            "displayFolder": "02. Population Growth & Targets",
            "expression": [
              "VAR LatestYr = [Selected Reporting Year]",
              "RETURN",
              "IF(",
              "    ISFILTERED(Dim_CalendarYear[Year]),",
              "    SUM(Fact_Population[YoY_Population_Change]),",
              "    CALCULATE(",
              "        SUM(Fact_Population[YoY_Population_Change]),",
              "        Dim_CalendarYear[Year] = LatestYr",
              "    )",
              ")"
            ],
            "formatString": "+#,##0;-#,##0;0",
            "lineageTag": "afa735bb-a22a-45ac-9d48-31a19414142d"
          },
          {
            "name": "YoY Population Growth %",
            "description": "Annual percentage growth rate of population.",
            "displayFolder": "02. Population Growth & Targets",
            "expression": "DIVIDE([YoY Population Change], [Prior Year Population], 0)",
            "formatString": "0.00%",
            "lineageTag": "804933ca-a8e7-41a3-8d2a-45bde09b66be"
          },
          {
            "name": "2022 Population Baseline",
            "description": "GMA adopted 2022 baseline population from Ordinance O20250002.",
            "displayFolder": "02. Population Growth & Targets",
            "expression": "SUM(Dim_GMA_2045_Target[Baseline_2022_Population])",
            "formatString": "#,##0",
            "lineageTag": "73516a8a-b87c-4f0d-8b81-117aa2694312"
          },
          {
            "name": "2045 Population Target",
            "description": "GMA 2045 adopted population growth target allocation.",
            "displayFolder": "02. Population Growth & Targets",
            "expression": "SUM(Dim_GMA_2045_Target[Target_2045_Population])",
            "formatString": "#,##0",
            "lineageTag": "0ebaa2ff-3d84-4e8e-b6c6-7960bc1247be"
          },
          {
            "name": "Projected 2045 Population Growth",
            "description": "Total growth allocation from 2022 to 2045.",
            "displayFolder": "02. Population Growth & Targets",
            "expression": "SUM(Dim_GMA_2045_Target[Projected_2045_Population_Growth])",
            "formatString": "#,##0",
            "lineageTag": "5bfaa2af-1396-49af-a7ee-eaa34d59228e"
          },
          {
            "name": "Population Growth Toward 2045 Target %",
            "description": "Percentage progress toward achieving the 2045 GMA population allocation.",
            "displayFolder": "02. Population Growth & Targets",
            "expression": [
              "VAR CurrentPop = [Total Population]",
              "VAR BasePop = [2022 Population Baseline]",
              "VAR TargetGain = [Projected 2045 Population Growth]",
              "RETURN",
              "IF(TargetGain > 0, DIVIDE(CurrentPop - BasePop, TargetGain, 0), BLANK())"
            ],
            "formatString": "0.0%",
            "lineageTag": "6cddf89e-edda-4cef-b152-d0c56dd454a2"
          },
          {
            "name": "Remaining Population Capacity to 2045",
            "description": "Remaining population growth allocation until 2045 target.",
            "displayFolder": "02. Population Growth & Targets",
            "expression": "[2045 Population Target] - [Total Population]",
            "formatString": "#,##0",
            "lineageTag": "baddbbde-bf13-4a35-b6d9-d53352a74f83"
          },
          {
            "name": "Total Housing Permits",
            "description": "Total residential units permitted in reporting period.",
            "displayFolder": "03. Housing Production & AMI",
            "expression": [
              "VAR LatestYr = [Selected Reporting Year]",
              "RETURN",
              "IF(",
              "    ISFILTERED(Dim_CalendarYear[Year]),",
              "    SUM(Fact_HousingPermits[Total_Permitted_Units]),",
              "    CALCULATE(",
              "        SUM(Fact_HousingPermits[Total_Permitted_Units]),",
              "        Dim_CalendarYear[Year] = LatestYr",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "314191e8-b1ee-4615-8361-9139c2558a6c"
          },
          {
            "name": "Single-Family Permits",
            "description": "Detached single-family residential permitted units.",
            "displayFolder": "03. Housing Production & AMI",
            "expression": [
              "VAR LatestYr = [Selected Reporting Year]",
              "RETURN",
              "IF(",
              "    ISFILTERED(Dim_CalendarYear[Year]),",
              "    SUM(Fact_HousingPermits[Single_Family_Units]),",
              "    CALCULATE(",
              "        SUM(Fact_HousingPermits[Single_Family_Units]),",
              "        Dim_CalendarYear[Year] = LatestYr",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "469ce267-3801-4888-a03d-0b46234dd2c3"
          },
          {
            "name": "Multi-Family Permits",
            "description": "Total multi-family permitted units (Duplex + 3-4 units + 5+ units).",
            "displayFolder": "03. Housing Production & AMI",
            "expression": [
              "VAR LatestYr = [Selected Reporting Year]",
              "RETURN",
              "IF(",
              "    ISFILTERED(Dim_CalendarYear[Year]),",
              "    SUM(Fact_HousingPermits[Duplex_Units]) + SUM(Fact_HousingPermits[MultiFamily_3_4_Units]) + SUM(Fact_HousingPermits[MultiFamily_5_Plus_Units]),",
              "    CALCULATE(",
              "        SUM(Fact_HousingPermits[Duplex_Units]) + SUM(Fact_HousingPermits[MultiFamily_3_4_Units]) + SUM(Fact_HousingPermits[MultiFamily_5_Plus_Units]),",
              "        Dim_CalendarYear[Year] = LatestYr",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "f8d15e47-15b4-4d19-83b8-461c981d276a"
          },
          {
            "name": "ADU Permits",
            "description": "Permitted Accessory Dwelling Units.",
            "displayFolder": "03. Housing Production & AMI",
            "expression": [
              "VAR LatestYr = [Selected Reporting Year]",
              "RETURN",
              "IF(",
              "    ISFILTERED(Dim_CalendarYear[Year]),",
              "    SUM(Fact_HousingPermits[ADU_Units]),",
              "    CALCULATE(",
              "        SUM(Fact_HousingPermits[ADU_Units]),",
              "        Dim_CalendarYear[Year] = LatestYr",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "dee63ad2-d68c-4de1-9cf5-0c276d5ff546"
          },
          {
            "name": "Demolished Units",
            "description": "Residential units demolished during reporting period.",
            "displayFolder": "03. Housing Production & AMI",
            "expression": [
              "VAR LatestYr = [Selected Reporting Year]",
              "RETURN",
              "IF(",
              "    ISFILTERED(Dim_CalendarYear[Year]),",
              "    SUM(Fact_HousingPermits[Demolished_Units]),",
              "    CALCULATE(",
              "        SUM(Fact_HousingPermits[Demolished_Units]),",
              "        Dim_CalendarYear[Year] = LatestYr",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "4b682041-6d0e-46a0-b40b-7face2189311"
          },
          {
            "name": "Net New Housing Units",
            "description": "Net new residential units (Total Permitted minus Demolitions).",
            "displayFolder": "03. Housing Production & AMI",
            "expression": [
              "VAR LatestYr = [Selected Reporting Year]",
              "RETURN",
              "IF(",
              "    ISFILTERED(Dim_CalendarYear[Year]),",
              "    SUM(Fact_HousingPermits[Net_New_Units]),",
              "    CALCULATE(",
              "        SUM(Fact_HousingPermits[Net_New_Units]),",
              "        Dim_CalendarYear[Year] = LatestYr",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "033ffa9d-f184-4e39-95db-f82666c820c0"
          },
          {
            "name": "Total Permit Valuation",
            "description": "Permit construction valuation in US Dollars.",
            "displayFolder": "03. Housing Production & AMI",
            "expression": [
              "VAR LatestYr = [Selected Reporting Year]",
              "RETURN",
              "IF(",
              "    ISFILTERED(Dim_CalendarYear[Year]),",
              "    SUM(Fact_HousingPermits[Total_Valuation_USD]),",
              "    CALCULATE(",
              "        SUM(Fact_HousingPermits[Total_Valuation_USD]),",
              "        Dim_CalendarYear[Year] = LatestYr",
              "    )",
              ")"
            ],
            "formatString": "$#,##0",
            "lineageTag": "e6befaa9-f363-494b-87fb-27e7a6bfe2d1"
          },
          {
            "name": "2045 Housing Target Units",
            "description": "GMA adopted net housing unit allocation 2020-2045 (17,450 countywide).",
            "displayFolder": "03. Housing Production & AMI",
            "expression": "SUM(Dim_GMA_2045_Target[Target_2045_Housing_Units])",
            "formatString": "#,##0",
            "lineageTag": "6838e52a-e35c-4a5b-9bd6-892a8b9ad4ff"
          },
          {
            "name": "Cumulative Net Housing Units (2020-Present)",
            "description": "Cumulative net new housing units added since GMA planning baseline 2020.",
            "displayFolder": "03. Housing Production & AMI",
            "expression": [
              "VAR MaxYr = IF(ISFILTERED(Dim_CalendarYear[Year]), [Selected Reporting Year], 2026)",
              "RETURN",
              "CALCULATE(",
              "    SUM(Fact_HousingPermits[Net_New_Units]),",
              "    FILTER(ALL(Dim_CalendarYear), Dim_CalendarYear[Year] >= 2020 && Dim_CalendarYear[Year] <= MaxYr)",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "cf92c6ab-0628-49da-b5d8-d5459c6e0c90"
          },
          {
            "name": "Housing Target Progress %",
            "description": "Percentage progress of cumulative housing production against 2045 GMA target.",
            "displayFolder": "03. Housing Production & AMI",
            "expression": "DIVIDE([Cumulative Net Housing Units (2020-Present)], [2045 Housing Target Units], 0)",
            "formatString": "0.0%",
            "lineageTag": "cd99baed-f9d8-4232-882b-912a0484013e"
          },
          {
            "name": "Low Income AMI Units (<80% AMI)",
            "description": "Housing units serving households below 80% of Area Median Income.",
            "displayFolder": "03. Housing Production & AMI",
            "expression": "SUM(Fact_Housing_AMI[AMI_0_to_30_Pct_Units]) + SUM(Fact_Housing_AMI[AMI_31_to_50_Pct_Units]) + SUM(Fact_Housing_AMI[AMI_51_to_80_Pct_Units])",
            "formatString": "#,##0",
            "lineageTag": "8e4f22b1-0147-4027-aaaf-86680ea466d5"
          },
          {
            "name": "Moderate to High Income AMI Units (>80% AMI)",
            "description": "Housing units serving households at or above 80% Area Median Income.",
            "displayFolder": "03. Housing Production & AMI",
            "expression": "SUM(Fact_Housing_AMI[AMI_81_to_100_Pct_Units]) + SUM(Fact_Housing_AMI[AMI_101_to_120_Pct_Units]) + SUM(Fact_Housing_AMI[AMI_Greater_120_Pct_Units])",
            "formatString": "#,##0",
            "lineageTag": "d5e3c058-43de-4f2d-8083-4041d765e189"
          },
          {
            "name": "Covered Employment QCEW",
            "description": "Annual average covered employment from ESD QCEW (County Total).",
            "displayFolder": "04. Employment & CAI Methodology",
            "expression": "CALCULATE(SUM(Fact_Employment[Annual_Average_Employment]), Fact_Employment[Is_County_Total] = 1)",
            "formatString": "#,##0",
            "lineageTag": "e09fc5ed-2199-4675-860d-f35f20749f7b"
          },
          {
            "name": "Estimated Total Employment (CAI Multiplier)",
            "description": "Estimated total employment including non-employer proprietors (CAI multiplier 1.15458).",
            "displayFolder": "04. Employment & CAI Methodology",
            "expression": "CALCULATE(SUM(Fact_Employment[Estimated_Total_Employment]), Fact_Employment[Is_County_Total] = 1)",
            "formatString": "#,##0",
            "lineageTag": "5cb9713b-59cc-47ac-970e-aa1402a3c5aa"
          },
          {
            "name": "2022 Employment Baseline",
            "description": "GMA adopted 2022 employment baseline (59,571 jobs countywide).",
            "displayFolder": "04. Employment & CAI Methodology",
            "expression": "SUM(Dim_GMA_2045_Target[Baseline_2022_Employment])",
            "formatString": "#,##0",
            "lineageTag": "9bd45745-23b5-486c-89d7-e45cab3bf1f6"
          },
          {
            "name": "2045 Employment Target",
            "description": "GMA adopted 2045 total employment target (80,100 jobs countywide).",
            "displayFolder": "04. Employment & CAI Methodology",
            "expression": "SUM(Dim_GMA_2045_Target[Target_2045_Employment])",
            "formatString": "#,##0",
            "lineageTag": "b2f30849-16f6-486c-9815-cc530439a70e"
          },
          {
            "name": "Total Establishments",
            "description": "Total employer establishments active in Skagit County.",
            "displayFolder": "04. Employment & CAI Methodology",
            "expression": "CALCULATE(SUM(Fact_Employment[Average_Establishments]), Fact_Employment[Is_County_Total] = 1)",
            "formatString": "#,##0",
            "lineageTag": "4a8a9f65-7730-4efa-ba62-7b26d390c5e3"
          },
          {
            "name": "Average Annual Wage USD",
            "description": "Average annual covered wage per worker in US Dollars.",
            "displayFolder": "04. Employment & CAI Methodology",
            "expression": "CALCULATE(AVERAGE(Fact_Employment[Average_Annual_Wage_USD]), Fact_Employment[Is_County_Total] = 1)",
            "formatString": "$#,##0",
            "lineageTag": "4e8cd15c-734c-4837-abb3-0992cdd2d0b9"
          },
          {
            "name": "Jurisdiction Share of Regional Population %",
            "description": "Jurisdiction percentage share of total Skagit County population.",
            "displayFolder": "05. Regional & Spatial Analysis",
            "expression": [
              "VAR RegionalPop = CALCULATE([Total Population], ALL(Dim_Jurisdiction), Fact_Population[Data_Source_Type] = \"OFM_April1_Official_Determination\")",
              "RETURN",
              "DIVIDE([Total Population], RegionalPop, 0)"
            ],
            "formatString": "0.0%",
            "lineageTag": "cca1161d-4718-4ba3-baf4-d8e3fdf6ed47"
          },
          {
            "name": "Jurisdiction Share of Regional Housing %",
            "description": "Jurisdiction percentage share of total net residential units built.",
            "displayFolder": "05. Regional & Spatial Analysis",
            "expression": [
              "DIVIDE(",
              "    [2045 Housing Target Units],",
              "    CALCULATE([2045 Housing Target Units], ALL(Dim_Jurisdiction)),",
              "    0",
              ")"
            ],
            "formatString": "0.0%",
            "lineageTag": "c1283962-1c33-477c-ab87-e9520b80bcf7"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #table({\"Measure_Group\"}, {{\"SCOG Growth Metrics\"}})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Jurisdiction",
        "columns": [
          {
            "name": "Jurisdiction_ID",
            "dataType": "string",
            "isKey": true,
            "lineageTag": "cb6a3cf2-827f-4000-a475-f123214891d9",
            "sourceColumn": "Jurisdiction_ID"
          },
          {
            "name": "Jurisdiction_Name",
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "7c02e404-996b-49de-9986-dc6fa7aa0b7b",
            "sourceColumn": "Jurisdiction_Name"
          },
          {
            "name": "Jurisdiction_Type",
            "dataType": "string",
            "lineageTag": "7d717c72-bb0c-4f41-a0fa-7aa97be05ef0",
            "sourceColumn": "Jurisdiction_Type"
          },
          {
            "name": "Is_Incorporated",
            "dataType": "int64",
            "lineageTag": "92c71610-de91-440f-acae-cb2c4fe33003",
            "sourceColumn": "Is_Incorporated"
          },
          {
            "name": "Is_UGA",
            "dataType": "int64",
            "lineageTag": "9aa03d9b-46f4-4a8e-8bcf-f705c20f56da",
            "sourceColumn": "Is_UGA"
          },
          {
            "name": "Latitude",
            "dataCategory": "Latitude",
            "dataType": "double",
            "lineageTag": "bf036e96-98b0-4ab9-a9d0-405c5f627034",
            "sourceColumn": "Latitude"
          },
          {
            "name": "Longitude",
            "dataCategory": "Longitude",
            "dataType": "double",
            "lineageTag": "574e6b85-e52e-4fef-b78d-e66dc2ecfdaa",
            "sourceColumn": "Longitude"
          },
          {
            "name": "County_Name",
            "dataCategory": "County",
            "dataType": "string",
            "lineageTag": "37226fb7-7155-40d0-8959-aac9ee92c367",
            "sourceColumn": "County_Name"
          },
          {
            "name": "State",
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "cbde60ab-c171-409d-8862-f06706c5a3b5",
            "sourceColumn": "State"
          }
        ],
        "description": "Official municipal, UGA, and rural entities within Skagit County.",
        "lineageTag": "6295089a-4372-40bc-91fe-2b0bb3ae933e",
        "partitions": [
          {
            "name": "Dim_Jurisdiction",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceWorkbookPath), null, true),",
                "    Sheet = Source{[Item=\"Dim_Jurisdiction\",Kind=\"Sheet\"]}[Data],",
                "    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),",
                "    Selected = Table.SelectColumns(Headers, {\"Jurisdiction_ID\", \"Jurisdiction_Name\", \"Jurisdiction_Type\", \"Is_Incorporated\", \"Is_UGA\", \"Latitude\", \"Longitude\", \"County_Name\", \"State\"}, MissingField.Error),",
                "    Typed = Table.TransformColumnTypes(Selected,{",
                "        {\"Jurisdiction_ID\", type text}, {\"Jurisdiction_Name\", type text}, {\"Jurisdiction_Type\", type text},",
                "        {\"Is_Incorporated\", Int64.Type}, {\"Is_UGA\", Int64.Type},",
                "        {\"Latitude\", type number}, {\"Longitude\", type number},",
                "        {\"County_Name\", type text}, {\"State\", type text}",
                "    })",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_CalendarYear",
        "columns": [
          {
            "name": "Year",
            "dataType": "int64",
            "isKey": true,
            "lineageTag": "9acb8722-1bd6-467b-9e1c-a863a294896b",
            "sourceColumn": "Year"
          },
          {
            "name": "Decade",
            "dataType": "string",
            "lineageTag": "1c9eb315-eca4-423f-a695-b878e666cdfd",
            "sourceColumn": "Decade"
          },
          {
            "name": "GMA_Planning_Cycle",
            "dataType": "string",
            "lineageTag": "ddc2f0eb-fad4-43f4-8f27-d6b7270fc47c",
            "sourceColumn": "GMA_Planning_Cycle"
          },
          {
            "name": "Is_Historical",
            "dataType": "int64",
            "lineageTag": "ac1eab83-7a2a-4bde-82a1-407d47921d85",
            "sourceColumn": "Is_Historical"
          },
          {
            "name": "Is_Prototype_Year_2025",
            "dataType": "int64",
            "lineageTag": "044da238-4b74-47a6-89af-a4e8233ffda9",
            "sourceColumn": "Is_Prototype_Year_2025"
          },
          {
            "name": "Is_Production_Year_2026",
            "dataType": "int64",
            "lineageTag": "4b8c89ea-688a-4461-81c2-3eafca25e8f7",
            "sourceColumn": "Is_Production_Year_2026"
          },
          {
            "name": "Is_Target_Year_2045",
            "dataType": "int64",
            "lineageTag": "a766f5f1-52f2-4344-8f1e-f7389698d331",
            "sourceColumn": "Is_Target_Year_2045"
          }
        ],
        "description": "Standardized calendar dimension spanning 1990 to 2045 GMA planning horizon.",
        "lineageTag": "2ecfc56b-ac48-41c4-a0d1-62bbc1fc7f6e",
        "partitions": [
          {
            "name": "Dim_CalendarYear",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceWorkbookPath), null, true),",
                "    Sheet = Source{[Item=\"Dim_CalendarYear\",Kind=\"Sheet\"]}[Data],",
                "    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),",
                "    Selected = Table.SelectColumns(Headers, {\"Year\", \"Decade\", \"GMA_Planning_Cycle\", \"Is_Historical\", \"Is_Prototype_Year_2025\", \"Is_Production_Year_2026\", \"Is_Target_Year_2045\"}, MissingField.Error),",
                "    Typed = Table.TransformColumnTypes(Selected,{",
                "        {\"Year\", Int64.Type}, {\"Decade\", type text}, {\"GMA_Planning_Cycle\", type text},",
                "        {\"Is_Historical\", Int64.Type}, {\"Is_Prototype_Year_2025\", Int64.Type},",
                "        {\"Is_Production_Year_2026\", Int64.Type}, {\"Is_Target_Year_2045\", Int64.Type}",
                "    })",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_GMA_2045_Target",
        "columns": [
          {
            "name": "Jurisdiction_ID",
            "dataType": "string",
            "lineageTag": "6c918261-689c-4838-813f-e5674f8a9ec4",
            "sourceColumn": "Jurisdiction_ID"
          },
          {
            "name": "Jurisdiction_Name",
            "dataType": "string",
            "lineageTag": "a6c81a3d-1f1c-4444-b2bf-dbf5449d8870",
            "sourceColumn": "Jurisdiction_Name"
          },
          {
            "name": "Jurisdiction_Type",
            "dataType": "string",
            "lineageTag": "b5945ea9-235b-46ca-8988-f14c0842f381",
            "sourceColumn": "Jurisdiction_Type"
          },
          {
            "name": "Baseline_2022_Population",
            "dataType": "int64",
            "lineageTag": "736af32b-79dc-41e0-ad2b-bf46bd541757",
            "sourceColumn": "Baseline_2022_Population"
          },
          {
            "name": "Target_2045_Population",
            "dataType": "int64",
            "lineageTag": "89ce9a4d-7767-4909-81c5-fabf7612314c",
            "sourceColumn": "Target_2045_Population"
          },
          {
            "name": "Projected_2045_Population_Growth",
            "dataType": "int64",
            "lineageTag": "b6ea9dd4-13e4-44ca-a75b-c685bbae3586",
            "sourceColumn": "Projected_2045_Population_Growth"
          },
          {
            "name": "Population_Growth_Share_Pct",
            "dataType": "double",
            "lineageTag": "26d5c2b8-ebc0-4001-9edb-52366943f422",
            "sourceColumn": "Population_Growth_Share_Pct"
          },
          {
            "name": "Target_2045_Housing_Units",
            "dataType": "int64",
            "lineageTag": "e01b9fca-de7b-4f39-a284-d27c1bc3d12e",
            "sourceColumn": "Target_2045_Housing_Units"
          },
          {
            "name": "Baseline_2022_Employment",
            "dataType": "int64",
            "lineageTag": "3f1e7ec2-89f9-4fd4-93a7-0cd06ab2ab49",
            "sourceColumn": "Baseline_2022_Employment"
          },
          {
            "name": "Target_2045_Employment",
            "dataType": "int64",
            "lineageTag": "c781229d-c2f6-44f1-9ca5-48d2c10391e3",
            "sourceColumn": "Target_2045_Employment"
          },
          {
            "name": "Projected_2045_Employment_Growth",
            "dataType": "int64",
            "lineageTag": "1924fc30-bdbc-4b47-afa1-27666a7de9fe",
            "sourceColumn": "Projected_2045_Employment_Growth"
          },
          {
            "name": "Employment_Growth_Share_Pct",
            "dataType": "double",
            "lineageTag": "bf5f3492-aec5-4019-8ebb-652d307d34f6",
            "sourceColumn": "Employment_Growth_Share_Pct"
          },
          {
            "name": "CAI_Self_Employment_Multiplier",
            "dataType": "double",
            "lineageTag": "8eb76fe4-b13e-4f7d-b794-cc4ceee31808",
            "sourceColumn": "CAI_Self_Employment_Multiplier"
          },
          {
            "name": "Data_Source",
            "dataType": "string",
            "lineageTag": "f7a47484-53cb-4245-a085-49fa880a66d0",
            "sourceColumn": "Data_Source"
          }
        ],
        "description": "Formally adopted Countywide Planning Policies growth targets (Ordinance O20250002).",
        "lineageTag": "2270d1b0-2130-4515-a5a8-e01a17a73afe",
        "partitions": [
          {
            "name": "Dim_GMA_2045_Target",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceWorkbookPath), null, true),",
                "    Sheet = Source{[Item=\"Dim_GMA_2045_Target\",Kind=\"Sheet\"]}[Data],",
                "    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),",
                "    Selected = Table.SelectColumns(Headers, {\"Jurisdiction_ID\", \"Jurisdiction_Name\", \"Jurisdiction_Type\", \"Baseline_2022_Population\", \"Target_2045_Population\", \"Projected_2045_Population_Growth\", \"Population_Growth_Share_Pct\", \"Target_2045_Housing_Units\", \"Baseline_2022_Employment\", \"Target_2045_Employment\", \"Projected_2045_Employment_Growth\", \"Employment_Growth_Share_Pct\", \"CAI_Self_Employment_Multiplier\", \"Data_Source\"}, MissingField.Error),",
                "    Typed = Table.TransformColumnTypes(Selected,{",
                "        {\"Jurisdiction_ID\", type text}, {\"Jurisdiction_Name\", type text}, {\"Jurisdiction_Type\", type text},",
                "        {\"Baseline_2022_Population\", Int64.Type}, {\"Target_2045_Population\", Int64.Type},",
                "        {\"Projected_2045_Population_Growth\", Int64.Type}, {\"Population_Growth_Share_Pct\", type number},",
                "        {\"Target_2045_Housing_Units\", Int64.Type}, {\"Baseline_2022_Employment\", Int64.Type},",
                "        {\"Target_2045_Employment\", Int64.Type}, {\"Projected_2045_Employment_Growth\", Int64.Type},",
                "        {\"Employment_Growth_Share_Pct\", type number}, {\"CAI_Self_Employment_Multiplier\", type number},",
                "        {\"Data_Source\", type text}",
                "    })",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_CAI_Employment_Benchmark",
        "columns": [
          {
            "name": "Benchmark_Key",
            "dataType": "string",
            "isKey": true,
            "lineageTag": "e4005286-c2a0-49c3-83e6-014821310a11",
            "sourceColumn": "Benchmark_Key"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "lineageTag": "50b7c3b3-64da-4cc7-9d38-a58860cfe5b9",
            "sourceColumn": "Year"
          },
          {
            "name": "Covered_Employment_QCEW",
            "dataType": "int64",
            "lineageTag": "d8ce84a4-a810-4aa4-ab16-676d6b3cb95e",
            "sourceColumn": "Covered_Employment_QCEW"
          },
          {
            "name": "Self_Employment_NES",
            "dataType": "int64",
            "lineageTag": "63d62ee2-b1e6-4d15-87a0-9914df6cb3ae",
            "sourceColumn": "Self_Employment_NES"
          },
          {
            "name": "Total_Employment_Combined",
            "dataType": "int64",
            "lineageTag": "2e5e6000-28cc-4e45-b429-2a6e455f6716",
            "sourceColumn": "Total_Employment_Combined"
          },
          {
            "name": "Self_Employment_Ratio",
            "dataType": "double",
            "lineageTag": "45d60727-14aa-411c-a755-53844122e7ce",
            "sourceColumn": "Self_Employment_Ratio"
          },
          {
            "name": "Ratio_Average_All_Years",
            "dataType": "double",
            "lineageTag": "5fafb2f8-c78a-419b-9d37-1f8a12df6419",
            "sourceColumn": "Ratio_Average_All_Years"
          },
          {
            "name": "Ratio_Average_Last_10_Obs",
            "dataType": "double",
            "lineageTag": "504dcb48-31b6-4187-94c8-ea0ad961892e",
            "sourceColumn": "Ratio_Average_Last_10_Obs"
          },
          {
            "name": "Is_Observed",
            "dataType": "int64",
            "lineageTag": "0a72f279-4511-4f35-bafd-34451f2dee94",
            "sourceColumn": "Is_Observed"
          },
          {
            "name": "Data_Source",
            "dataType": "string",
            "lineageTag": "d4333de9-feb0-4e5a-a1e6-b4bb376a83c2",
            "sourceColumn": "Data_Source"
          }
        ],
        "description": "CAI Total Employment Calculation historical series (1999-2022) with QCEW and NES.",
        "lineageTag": "89cbfdac-c4c0-46a7-995f-147f11702d38",
        "partitions": [
          {
            "name": "Dim_CAI_Employment_Benchmark",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceWorkbookPath), null, true),",
                "    Sheet = Source{[Item=\"Dim_CAI_Employment_Benchmark\",Kind=\"Sheet\"]}[Data],",
                "    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),",
                "    Selected = Table.SelectColumns(Headers, {\"Benchmark_Key\", \"Year\", \"Covered_Employment_QCEW\", \"Self_Employment_NES\", \"Total_Employment_Combined\", \"Self_Employment_Ratio\", \"Ratio_Average_All_Years\", \"Ratio_Average_Last_10_Obs\", \"Is_Observed\", \"Data_Source\"}, MissingField.Error),",
                "    Typed = Table.TransformColumnTypes(Selected,{",
                "        {\"Benchmark_Key\", type text}, {\"Year\", Int64.Type},",
                "        {\"Covered_Employment_QCEW\", Int64.Type}, {\"Self_Employment_NES\", Int64.Type},",
                "        {\"Total_Employment_Combined\", Int64.Type}, {\"Self_Employment_Ratio\", type number},",
                "        {\"Ratio_Average_All_Years\", type number}, {\"Ratio_Average_Last_10_Obs\", type number},",
                "        {\"Is_Observed\", Int64.Type}, {\"Data_Source\", type text}",
                "    })",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact_Population",
        "columns": [
          {
            "name": "Fact_Population_Key",
            "dataType": "string",
            "isKey": true,
            "lineageTag": "1fc043c9-a921-4294-90af-1369c50f25ec",
            "sourceColumn": "Fact_Population_Key"
          },
          {
            "name": "Jurisdiction_ID",
            "dataType": "string",
            "lineageTag": "ddfe5c6d-8585-47a3-b863-51f85b14ea9c",
            "sourceColumn": "Jurisdiction_ID"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "lineageTag": "e3c2fa7f-43fd-4d0b-b710-8187aac868fb",
            "sourceColumn": "Year"
          },
          {
            "name": "Jurisdiction_Name",
            "dataType": "string",
            "lineageTag": "11772293-a79b-4168-ba3c-439a5ed41dca",
            "sourceColumn": "Jurisdiction_Name"
          },
          {
            "name": "Population_Count",
            "dataType": "int64",
            "lineageTag": "0ab47cab-a6cd-4357-890f-79b8d25430cd",
            "sourceColumn": "Population_Count"
          },
          {
            "name": "Prior_Year_Population",
            "dataType": "int64",
            "lineageTag": "c358de23-31ca-4aec-9ece-e352e35a1f06",
            "sourceColumn": "Prior_Year_Population"
          },
          {
            "name": "YoY_Population_Change",
            "dataType": "int64",
            "lineageTag": "1312d592-7a58-4451-97b1-9af0d100a971",
            "sourceColumn": "YoY_Population_Change"
          },
          {
            "name": "YoY_Growth_Rate_Pct",
            "dataType": "double",
            "lineageTag": "9f04c0c3-1533-45de-b5da-5d46ac28488f",
            "sourceColumn": "YoY_Growth_Rate_Pct"
          },
          {
            "name": "Data_Source_Type",
            "dataType": "string",
            "lineageTag": "15eef53e-b09b-48fc-b649-e4d485494ac0",
            "sourceColumn": "Data_Source_Type"
          }
        ],
        "description": "Annual population determinations by jurisdiction from OFM April 1.",
        "lineageTag": "6371eae3-6932-435b-8464-3704b9558212",
        "partitions": [
          {
            "name": "Fact_Population",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceWorkbookPath), null, true),",
                "    Sheet = Source{[Item=\"Fact_Population\",Kind=\"Sheet\"]}[Data],",
                "    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),",
                "    Selected = Table.SelectColumns(Headers, {\"Fact_Population_Key\", \"Jurisdiction_ID\", \"Year\", \"Jurisdiction_Name\", \"Population_Count\", \"Prior_Year_Population\", \"YoY_Population_Change\", \"YoY_Growth_Rate_Pct\", \"Data_Source_Type\"}, MissingField.Error),",
                "    Typed = Table.TransformColumnTypes(Selected,{",
                "        {\"Fact_Population_Key\", type text}, {\"Jurisdiction_ID\", type text}, {\"Year\", Int64.Type},",
                "        {\"Jurisdiction_Name\", type text}, {\"Population_Count\", Int64.Type},",
                "        {\"Prior_Year_Population\", Int64.Type}, {\"YoY_Population_Change\", Int64.Type},",
                "        {\"YoY_Growth_Rate_Pct\", type number}, {\"Data_Source_Type\", type text}",
                "    })",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact_HousingPermits",
        "columns": [
          {
            "name": "Fact_Housing_Key",
            "dataType": "string",
            "isKey": true,
            "lineageTag": "793079c3-5423-44c5-9ec9-811e4d288c0e",
            "sourceColumn": "Fact_Housing_Key"
          },
          {
            "name": "Jurisdiction_ID",
            "dataType": "string",
            "lineageTag": "f915fe14-0b80-4da6-8dee-7973aafbd8c7",
            "sourceColumn": "Jurisdiction_ID"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "lineageTag": "b855b913-f4bf-4310-95ab-f7696bf418d8",
            "sourceColumn": "Year"
          },
          {
            "name": "Jurisdiction_Name",
            "dataType": "string",
            "lineageTag": "ea2680ab-9955-443c-bfd7-0693f433cc48",
            "sourceColumn": "Jurisdiction_Name"
          },
          {
            "name": "Single_Family_Units",
            "dataType": "int64",
            "lineageTag": "9a0aaf06-cddb-4b93-a3d3-c29b784a7ca9",
            "sourceColumn": "Single_Family_Units"
          },
          {
            "name": "Duplex_Units",
            "dataType": "int64",
            "lineageTag": "05ebfeed-dad9-4170-b3e3-50238c417b64",
            "sourceColumn": "Duplex_Units"
          },
          {
            "name": "MultiFamily_3_4_Units",
            "dataType": "int64",
            "lineageTag": "76a9bb90-8baa-4fab-a4fc-ab97718e9965",
            "sourceColumn": "MultiFamily_3_4_Units"
          },
          {
            "name": "MultiFamily_5_Plus_Units",
            "dataType": "int64",
            "lineageTag": "62e6e669-a3f7-4b06-bb17-939a64b3f147",
            "sourceColumn": "MultiFamily_5_Plus_Units"
          },
          {
            "name": "ADU_Units",
            "dataType": "int64",
            "lineageTag": "7cd7159c-2435-4ba3-a376-b553347b2033",
            "sourceColumn": "ADU_Units"
          },
          {
            "name": "Mobile_Home_Units",
            "dataType": "int64",
            "lineageTag": "cab1558c-f5a1-4e2f-b536-ac1ea7d74672",
            "sourceColumn": "Mobile_Home_Units"
          },
          {
            "name": "Total_Permitted_Units",
            "dataType": "int64",
            "lineageTag": "39523820-0d35-4a30-8c16-50e86940b1c1",
            "sourceColumn": "Total_Permitted_Units"
          },
          {
            "name": "Completed_Units",
            "dataType": "int64",
            "lineageTag": "f921fb70-2159-4677-acd0-4b673ab55dc5",
            "sourceColumn": "Completed_Units"
          },
          {
            "name": "Demolished_Units",
            "dataType": "int64",
            "lineageTag": "280db824-e657-430f-b088-280f0ea2e3f4",
            "sourceColumn": "Demolished_Units"
          },
          {
            "name": "Net_New_Units",
            "dataType": "int64",
            "lineageTag": "35307ebc-0dd6-4e69-900e-ac6aca8b8a80",
            "sourceColumn": "Net_New_Units"
          },
          {
            "name": "Total_Valuation_USD",
            "dataType": "int64",
            "lineageTag": "fce363c4-8db3-436f-9e56-3a8d839896e7",
            "sourceColumn": "Total_Valuation_USD"
          },
          {
            "name": "Data_Source",
            "dataType": "string",
            "lineageTag": "814acee6-8083-44df-9546-1fc22474e1cf",
            "sourceColumn": "Data_Source"
          }
        ],
        "description": "Annual residential building permit issuance by typology and valuation.",
        "lineageTag": "9e443c8f-cc49-45ba-86f0-8a6b8dc6d9d7",
        "partitions": [
          {
            "name": "Fact_HousingPermits",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceWorkbookPath), null, true),",
                "    Sheet = Source{[Item=\"Fact_HousingPermits\",Kind=\"Sheet\"]}[Data],",
                "    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),",
                "    Selected = Table.SelectColumns(Headers, {\"Fact_Housing_Key\", \"Jurisdiction_ID\", \"Year\", \"Jurisdiction_Name\", \"Single_Family_Units\", \"Duplex_Units\", \"MultiFamily_3_4_Units\", \"MultiFamily_5_Plus_Units\", \"ADU_Units\", \"Mobile_Home_Units\", \"Total_Permitted_Units\", \"Completed_Units\", \"Demolished_Units\", \"Net_New_Units\", \"Total_Valuation_USD\", \"Data_Source\"}, MissingField.Error),",
                "    Typed = Table.TransformColumnTypes(Selected,{",
                "        {\"Fact_Housing_Key\", type text}, {\"Jurisdiction_ID\", type text}, {\"Year\", Int64.Type},",
                "        {\"Jurisdiction_Name\", type text}, {\"Single_Family_Units\", Int64.Type},",
                "        {\"Duplex_Units\", Int64.Type}, {\"MultiFamily_3_4_Units\", Int64.Type},",
                "        {\"MultiFamily_5_Plus_Units\", Int64.Type}, {\"ADU_Units\", Int64.Type},",
                "        {\"Mobile_Home_Units\", Int64.Type}, {\"Total_Permitted_Units\", Int64.Type},",
                "        {\"Completed_Units\", Int64.Type}, {\"Demolished_Units\", Int64.Type},",
                "        {\"Net_New_Units\", Int64.Type}, {\"Total_Valuation_USD\", Int64.Type},",
                "        {\"Data_Source\", type text}",
                "    })",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact_Employment",
        "columns": [
          {
            "name": "Fact_Employment_Key",
            "dataType": "string",
            "isKey": true,
            "lineageTag": "7201d22c-08c3-4c86-99f9-40c75c93dc0a",
            "sourceColumn": "Fact_Employment_Key"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "lineageTag": "88f1dc92-cd46-4ae7-9dda-716b060d3376",
            "sourceColumn": "Year"
          },
          {
            "name": "Period_Type",
            "dataType": "string",
            "lineageTag": "dd67312f-2095-4862-b8dd-a50a3b3714f9",
            "sourceColumn": "Period_Type"
          },
          {
            "name": "Industry_Key",
            "dataType": "string",
            "lineageTag": "e48f0472-1d6c-4063-bd7a-52fa867180f1",
            "sourceColumn": "Industry_Key"
          },
          {
            "name": "Row_Level",
            "dataType": "string",
            "lineageTag": "9eb03eda-07e6-454c-841e-80772cb9462f",
            "sourceColumn": "Row_Level"
          },
          {
            "name": "Parent_2Digit_Code",
            "dataType": "string",
            "lineageTag": "d15b1b3e-5bab-4181-bdae-533647eb9901",
            "sourceColumn": "Parent_2Digit_Code"
          },
          {
            "name": "NAICS_2Digit_Code",
            "dataType": "string",
            "lineageTag": "2dac487c-cedf-4481-9377-b13a3977ca38",
            "sourceColumn": "NAICS_2Digit_Code"
          },
          {
            "name": "NAICS_3Digit_Code",
            "dataType": "string",
            "lineageTag": "1947015e-ba37-4ee7-a749-736c3a26e85c",
            "sourceColumn": "NAICS_3Digit_Code"
          },
          {
            "name": "Industry_Subsector_Title",
            "dataType": "string",
            "lineageTag": "c81909dc-1d6c-4656-ae8a-5411c0fca3c7",
            "sourceColumn": "Industry_Subsector_Title"
          },
          {
            "name": "Title_As_Reported",
            "dataType": "string",
            "lineageTag": "15fd6f86-a192-4bb5-aaf2-847eff6a58da",
            "sourceColumn": "Title_As_Reported"
          },
          {
            "name": "Is_County_Total",
            "dataType": "int64",
            "lineageTag": "0ac92c43-3632-4b3d-b890-9d6264e11e19",
            "sourceColumn": "Is_County_Total"
          },
          {
            "name": "Is_Suppressed",
            "dataType": "int64",
            "lineageTag": "2981d5d2-1ba8-466c-bc59-ff5bb6e1270c",
            "sourceColumn": "Is_Suppressed"
          },
          {
            "name": "Average_Establishments",
            "dataType": "int64",
            "lineageTag": "c0917f65-b189-4a11-8f50-c9fbaa0c4c0a",
            "sourceColumn": "Average_Establishments"
          },
          {
            "name": "Annual_Average_Employment",
            "dataType": "int64",
            "lineageTag": "d4bd78ff-3619-4e1b-87e9-020f25a53b86",
            "sourceColumn": "Annual_Average_Employment"
          },
          {
            "name": "Q1_Average_Employment",
            "dataType": "int64",
            "lineageTag": "af985235-8a72-4e46-914e-659f88c60076",
            "sourceColumn": "Q1_Average_Employment"
          },
          {
            "name": "Estimated_Total_Employment",
            "dataType": "int64",
            "lineageTag": "43f641dd-da80-42ad-8161-8ae20402777c",
            "sourceColumn": "Estimated_Total_Employment"
          },
          {
            "name": "Estimated_Total_Employment_Q1",
            "dataType": "int64",
            "lineageTag": "245ba260-e9fe-4b75-b61b-0f7345179f72",
            "sourceColumn": "Estimated_Total_Employment_Q1"
          },
          {
            "name": "CAI_Self_Employment_Multiplier",
            "dataType": "double",
            "lineageTag": "36b49898-e846-4f38-a366-1c27f8a64b61",
            "sourceColumn": "CAI_Self_Employment_Multiplier"
          },
          {
            "name": "Average_Annual_Wage_USD",
            "dataType": "int64",
            "lineageTag": "1fdd16c4-9c09-4360-b60d-a0e85ff2b3d7",
            "sourceColumn": "Average_Annual_Wage_USD"
          },
          {
            "name": "Data_Status",
            "dataType": "string",
            "lineageTag": "ac2e5620-34ba-4f04-8f23-efb1622e1374",
            "sourceColumn": "Data_Status"
          }
        ],
        "description": "Employment Security Department (ESD QCEW) covered jobs by NAICS industry sector.",
        "lineageTag": "fd875f38-79ba-4b1f-b394-0c430f6de12d",
        "partitions": [
          {
            "name": "Fact_Employment",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceWorkbookPath), null, true),",
                "    Sheet = Source{[Item=\"Fact_Employment\",Kind=\"Sheet\"]}[Data],",
                "    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),",
                "    Selected = Table.SelectColumns(Headers, {\"Fact_Employment_Key\", \"Year\", \"Period_Type\", \"Industry_Key\", \"Row_Level\", \"Parent_2Digit_Code\", \"NAICS_2Digit_Code\", \"NAICS_3Digit_Code\", \"Industry_Subsector_Title\", \"Title_As_Reported\", \"Is_County_Total\", \"Is_Suppressed\", \"Average_Establishments\", \"Annual_Average_Employment\", \"Q1_Average_Employment\", \"Estimated_Total_Employment\", \"Estimated_Total_Employment_Q1\", \"CAI_Self_Employment_Multiplier\", \"Average_Annual_Wage_USD\", \"Data_Status\"}, MissingField.Error),",
                "    Typed = Table.TransformColumnTypes(Selected,{",
                "        {\"Fact_Employment_Key\", type text}, {\"Year\", Int64.Type}, {\"Period_Type\", type text},",
                "        {\"Industry_Key\", type text}, {\"Row_Level\", type text}, {\"Parent_2Digit_Code\", type text},",
                "        {\"NAICS_2Digit_Code\", type text}, {\"NAICS_3Digit_Code\", type text},",
                "        {\"Industry_Subsector_Title\", type text}, {\"Title_As_Reported\", type text},",
                "        {\"Is_County_Total\", Int64.Type}, {\"Is_Suppressed\", Int64.Type},",
                "        {\"Average_Establishments\", Int64.Type}, {\"Annual_Average_Employment\", Int64.Type},",
                "        {\"Q1_Average_Employment\", Int64.Type}, {\"Estimated_Total_Employment\", Int64.Type},",
                "        {\"Estimated_Total_Employment_Q1\", Int64.Type}, {\"CAI_Self_Employment_Multiplier\", type number},",
                "        {\"Average_Annual_Wage_USD\", Int64.Type}, {\"Data_Status\", type text}",
                "    })",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact_Housing_AMI",
        "columns": [
          {
            "name": "Fact_AMI_Key",
            "dataType": "string",
            "isKey": true,
            "lineageTag": "a1851cef-b8ae-471f-86bc-bc7b112dc6f2",
            "sourceColumn": "Fact_AMI_Key"
          },
          {
            "name": "Jurisdiction_ID",
            "dataType": "string",
            "lineageTag": "58ebbd7d-2b8d-456c-bb0b-c577d0537a9f",
            "sourceColumn": "Jurisdiction_ID"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "lineageTag": "1c704dee-0b16-4ae6-85fb-e8cb31475e6c",
            "sourceColumn": "Year"
          },
          {
            "name": "Jurisdiction_Name",
            "dataType": "string",
            "lineageTag": "a2f7e8db-34ed-46e3-923e-d1b69d889387",
            "sourceColumn": "Jurisdiction_Name"
          },
          {
            "name": "Structure_Type",
            "dataType": "string",
            "lineageTag": "84cf7a2a-2b80-46ce-a7dd-33f9d310e23b",
            "sourceColumn": "Structure_Type"
          },
          {
            "name": "AMI_0_to_30_Pct_Units",
            "dataType": "int64",
            "lineageTag": "911331dc-d3cb-4b3f-bbcf-388af316dfbe",
            "sourceColumn": "AMI_0_to_30_Pct_Units"
          },
          {
            "name": "AMI_31_to_50_Pct_Units",
            "dataType": "int64",
            "lineageTag": "e64b3fa1-8af3-491c-9a0c-914af628f8c8",
            "sourceColumn": "AMI_31_to_50_Pct_Units"
          },
          {
            "name": "AMI_51_to_80_Pct_Units",
            "dataType": "int64",
            "lineageTag": "73e71439-7b29-4517-b657-a18653685f7a",
            "sourceColumn": "AMI_51_to_80_Pct_Units"
          },
          {
            "name": "AMI_81_to_100_Pct_Units",
            "dataType": "int64",
            "lineageTag": "bb033785-5f68-4db1-bf64-a51d92880bb3",
            "sourceColumn": "AMI_81_to_100_Pct_Units"
          },
          {
            "name": "AMI_101_to_120_Pct_Units",
            "dataType": "int64",
            "lineageTag": "418323b8-339f-4fb7-87e3-87dd8c57fd59",
            "sourceColumn": "AMI_101_to_120_Pct_Units"
          },
          {
            "name": "AMI_Greater_120_Pct_Units",
            "dataType": "int64",
            "lineageTag": "438a0214-028d-4b85-9d21-c45b7ac00f25",
            "sourceColumn": "AMI_Greater_120_Pct_Units"
          },
          {
            "name": "Total_AMI_Units",
            "dataType": "int64",
            "lineageTag": "af7efa73-df50-4ddd-920a-d76471cb2788",
            "sourceColumn": "Total_AMI_Units"
          },
          {
            "name": "Reconciliation_Status",
            "dataType": "string",
            "lineageTag": "95b8942d-e379-401a-a129-285333273b4b",
            "sourceColumn": "Reconciliation_Status"
          }
        ],
        "description": "Affordable housing unit production classified by Area Median Income (AMI) tiers.",
        "lineageTag": "94a4d5ac-a323-4f8c-a5bc-159475876305",
        "partitions": [
          {
            "name": "Fact_Housing_AMI",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceWorkbookPath), null, true),",
                "    Sheet = Source{[Item=\"Fact_Housing_AMI\",Kind=\"Sheet\"]}[Data],",
                "    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),",
                "    Selected = Table.SelectColumns(Headers, {\"Fact_AMI_Key\", \"Jurisdiction_ID\", \"Year\", \"Jurisdiction_Name\", \"Structure_Type\", \"AMI_0_to_30_Pct_Units\", \"AMI_31_to_50_Pct_Units\", \"AMI_51_to_80_Pct_Units\", \"AMI_81_to_100_Pct_Units\", \"AMI_101_to_120_Pct_Units\", \"AMI_Greater_120_Pct_Units\", \"Total_AMI_Units\", \"Reconciliation_Status\"}, MissingField.Error),",
                "    Typed = Table.TransformColumnTypes(Selected,{",
                "        {\"Fact_AMI_Key\", type text}, {\"Jurisdiction_ID\", type text}, {\"Year\", Int64.Type},",
                "        {\"Jurisdiction_Name\", type text}, {\"Structure_Type\", type text},",
                "        {\"AMI_0_to_30_Pct_Units\", Int64.Type}, {\"AMI_31_to_50_Pct_Units\", Int64.Type},",
                "        {\"AMI_51_to_80_Pct_Units\", Int64.Type}, {\"AMI_81_to_100_Pct_Units\", Int64.Type},",
                "        {\"AMI_101_to_120_Pct_Units\", Int64.Type}, {\"AMI_Greater_120_Pct_Units\", Int64.Type},",
                "        {\"Total_AMI_Units\", Int64.Type}, {\"Reconciliation_Status\", type text}",
                "    })",
                "in",
                "    Typed"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}